version: '3'
services:
  db_miracle:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5433:5432"
    volumes: 
      - ../postgresql_miracles:/var/lib/postgresql/data
  api:
    depends_on:
      - db_miracle
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PASSWORD: postgres
    links:
      - db_miracle:postgres
    ports:
      - "127.0.0.1:8080:8080"
