version: '3'
services:
  db_miracle:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 54320:5432
    volumes:
      - /var/postgresql_miracles:/var/lib/postgresql/data
  api:
    depends_on:
      - db_miracle
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PASSWORD: postgres
    links:
      - db_miracle:postgres
    ports:
      - 8080:8080