version: '3'
services:
  db_miracle:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 54320:5432
    volumes:
      - /var/postgresql_miracles:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - 127.0.0.1:6379:6379
    working_dir: /var/lib/redis
  api:
    depends_on:
      - db_miracle
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PASSWORD: postgres
    links:
      - db_miracle:postgres
    ports:
      - 8080:8080